name: Deploy Cloud Function CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'requirements.txt'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Cloud Functions Gen 2
        run: |
          gcloud functions deploy ingest-cne-pipeline \
            --gen2 \
            --runtime=python311 \
            --region=us-central1 \
            --source=. \
            --entry-point=ingest_cne_data \
            --trigger-http \
            --set-env-vars=BUCKET_NAME=cne-datalake-raw-mx-2026,PROJECT_ID=cne-pipeline-mx-2026 \
            --memory=512MiB \
            --no-allow-unauthenticated