name: Deploy Cloud Function CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: ingest-cne-pipeline
          runtime: python311
          region: us-central1
          entry_point: ingest_cne_data
          env_vars: BUCKET_NAME=cne-historical-data-lake,PROJECT_ID=cne-pipeline-mx-2026